spring:
  application:
    name: user-ident-app
    
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
  h2:
    console:
      enabled: true
     
server:
  port: 8080
  #servlet:
  #  context-path: /user-ident-app

app-token:
  secret: "jf9i4jgu83nfl0"
  prefix: "Bearer "
  expirationTime: 864000000 # 10 days
  password-reset-expiration-time: 3600000 # 1 hour

login-url: "/users/" # url to login to application is /users/login instead of /login

email-verification:
  enable: false
  url: "/users/email-verification"
  link: "http://localhost:8080/users/email-verification?token="
password-reset:
  link: "http://localhost:8080/verification-service/password-reset.html?token="
  request-url: "/users/password-reset-request"
  url: "/users/password-reset"

  