spring:
  application:
    name: user-ident-app
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 8080
  #servlet:
  #  context-path: /user-ident-app

token:
  secret: "jf9i4jgu83nfl0"
  prefix: "Bearer "
  expirationTime: 864000000 # 10 days
 
loginUrl: "/users"